[build-system]
requires = [
   "setuptools==75.1.0",
   "wheel==0.44.0",
   "tomli==2.0.2; python_version<'3.11'",
   "packaging==24.1",
   "json-with-comments==1.2.9",
]

[project]
name = "MusicBot-DB"
description = "Package that installs DB library and jsonc as dependencies"
version = "0.0.3"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = "db.txt"}
